config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "calculations#welcome_page"
  resources :calculations
  resource :users, path: :profile
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    %w[id email created_at updated_at] # Add other attributes as needed
  end
      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calculation.rb
class Calculation < ApplicationRecord
  validates :firstname, :lastname, :middlename, :phone_number, :email, :weight, :length, :width, :height, :dep_point, :dest_point, presence: true
  belongs_to :user

  after_create :send_email

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "dep_point", "dest_point", "distance", "email", "firstname", "height", "id", "lastname", "length", "middlename", "phone_number", "price", "updated_at", "user_id", "weight", "width"]
  end

  private

  def send_email
    NotifyWorker.perform_async(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :calculations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculations_controller.rb
require './calculations/cargo_calculator'

class CalculationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_calculation, only: %i[ show edit update destroy set_price]

  # GET /calculations or /calculations.json
  def index
    @q = current_user.calculations.ransack(params[:q])
    @calculations = @q.result.order(id: :asc).page(params[:page]).per(2)
  end

  # GET /calculations/1 or /calculations/1.json
  def show
  end

  # GET /calculations/new
  def new
    @calculation = Calculation.new
  end

  # GET /calculations/1/edit
  def edit
  end

  # POST /calculations or /calculations.json
  def create
    @calculation = Calculation.new(calculation_params)

    respond_to do |format|
      if @calculation.save
        set_price
        format.html { redirect_to calculation_url(@calculation), notice: "Calculation was successfully created." }
        format.json { render :show, status: :created, location: @calculation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calculations/1 or /calculations/1.json
  def update
    respond_to do |format|
      if @calculation.update(calculation_params)
        format.html { redirect_to calculation_url(@calculation), notice: "Calculation was successfully updated." }
        format.json { render :show, status: :ok, location: @calculation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calculations/1 or /calculations/1.json
  def destroy
    @calculation.destroy

    respond_to do |format|
      format.html { redirect_to calculations_url, notice: "Calculation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def welcome_page
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculation
      @calculation = Calculation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calculation_params
      params.require(:calculation).permit(:firstname, :lastname, :middlename, :phone_number, :email, :weight, :length, :width, :height, :dep_point, :dest_point, :user_id)
    end

    def set_price
      # CargoCalculator object
      cargo_calculator = Calculations::CargoCalculator.new
      cargo_calculator.weight = @calculation.weight

      cargo_calculator.length = @calculation.length
      cargo_calculator.width = @calculation.width
      cargo_calculator.height = @calculation.height
      cargo_calculator.calculate_distance
      cargo_calculator.calculate_price

      @calculation.update(price: cargo_calculator.price, distance: cargo_calculator.distance)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def show

  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: "user was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:avatar)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/views/calculations/_calculation.html.erb
<div id="<%= dom_id calculation %>">
  <p>
    <strong>Firstname:</strong>
    <%= calculation.firstname %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= calculation.lastname %>
  </p>

  <p>
    <strong>Middlename:</strong>
    <%= calculation.middlename %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= calculation.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= calculation.email %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= calculation.weight %>
  </p>

  <p>
    <strong>Length:</strong>
    <%= calculation.length %>
  </p>

  <p>
    <strong>Width:</strong>
    <%= calculation.width %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= calculation.height %>
  </p>

  <p>
    <strong>Dep point:</strong>
    <%= calculation.dep_point %>
  </p>

  <p>
    <strong>Dest point:</strong>
    <%= calculation.dest_point %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= calculation.price %>
  </p>
</div>

app/views/calculations/_form.html.erb
<%= form_with(model: calculation) do |form| %>
  <% if calculation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(calculation.errors.count, "error") %> prohibited this calculation from being saved:</h2>

      <ul>
        <% calculation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :firstname, style: "display: block" %>
    <%= form.text_field :firstname %>
  </div>

  <div>
    <%= form.label :lastname, style: "display: block" %>
    <%= form.text_field :lastname %>
  </div>

  <div>
    <%= form.label :middlename, style: "display: block" %>
    <%= form.text_field :middlename %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :length, style: "display: block" %>
    <%= form.text_field :length %>
  </div>

  <div>
    <%= form.label :width, style: "display: block" %>
    <%= form.text_field :width %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :dep_point, style: "display: block" %>
    <%= form.text_field :dep_point %>
  </div>

  <div>
    <%= form.label :dest_point, style: "display: block" %>
    <%= form.text_field :dest_point %>
  </div>
  <%= current_user.id %>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/calculations/edit.html.erb
<h1>Editing calculation</h1>

<%= render "form", calculation: @calculation %>

<br>

<div>
  <%= link_to "Show this calculation", @calculation %> |
  <%= link_to "Back to calculations", calculations_path %>
</div>

app/views/calculations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Calculations</h1>

<div id="calculations">
  <table>
    <thead>
      <th>ID</th>
      <th>Department</th>
      <th>Destination</th>
      <th><%= sort_link(@q, :distance, 'Distance') %></th>
      <th><%= sort_link(@q, :price, 'Price') %></th>
      <th><%= sort_link(@q, :created_at, 'created_at') %></th>
      <th colspan="1"></th>
    </thead>
    <tbody>
      <% @calculations.each do |calculation| %>
        <tr>
          <td><%= calculation.id %></td>
          <td><%= calculation.dep_point %></td>
          <td><%= calculation.dest_point %></td>
          <td><%= calculation.distance %></td>
          <td><%= calculation.price %></td>
          <td><%= calculation.created_at %></td>
          <td><%= link_to 'show', calculation_path(calculation) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @calculations %>
<%= link_to "New calculation", new_calculation_path %>

app/views/calculations/new.html.erb
<h1>New calculation</h1>

<%= render "form", calculation: @calculation %>

<br>

<div>
  <%= link_to "Back to calculations", calculations_path %>
</div>

app/views/calculations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @calculation %>

<div>
  <%= link_to "Edit this calculation", edit_calculation_path(@calculation) %> |
  <%= link_to "Back to calculations", calculations_path %>

  <%= button_to "Destroy this calculation", @calculation, method: :delete %>
</div>

app/views/calculations/welcome_page.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
    <%= link_to 'Calculations', calculations_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Edit', edit_user_registration_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'logout', destroy_user_session_path, class: 'nav-link', data: { turbo_method: :delete } %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to "SignUp", new_user_registration_path, class: 'nav-link' %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CargoCalculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, url: users_path) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :avatar, style: "display: block" %>
    <%= form.file_field :avatar, multipart: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Profile</h1>

<%= render "form", user: current_user %>

<br>

<div>
  <%# link_to "Show this profile", current_user %>
</div>